name: Page Performance Report

on:
  schedule:
    - cron: '0 2 15,30 * *'  # Runs at 2 AM UTC on 15th and 30th
  workflow_dispatch:

jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run report
      run: node report.js
      env:
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
